services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    env_file:
      - .env
    environment:
      - FILESTORE_ADDRESS=filestore:9000
      - FILESTORE_ACCESS_KEY=root
      - FILESTORE_SECRET_KEY=rootroot
    ports:
      - ${API_PORT:-8999}:80
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: src
          target: /app/src
        - action: sync
          path: assets
          target: /app/assets
        - action: sync
          path: public
          target: /app/public
        - action: rebuild
          path: pdm.lock

  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER:-root}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-recipes}
    ports:
      - ${DB_PORT:-3366}:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    # volumes:
    #   - ./docker-storage/mysql:/var/lib/mysql

  filestore:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=${FILESTORE_ACCESS_KEY:-root}
      - MINIO_ROOT_PASSWORD=${FILESTORE_SECRET_KEY:-rootroot}
    command: server --address filestore:9000 --console-address :9001 /data
    healthcheck:
      test: mc ready local
      interval: 10s
      timeout: 10s
      retries: 6
    ports:
      - ${FILESTORE_PORT:-9011}:9001
