@host=http://{{hostname}}:{{port}}
@assetsDir=./../../../assets

### get all ingredients
GET /v1/ingredients

### post a potato
POST /v1/ingredients
    ?name=Potato

### post some pasta with more information
POST /v1/ingredients
    ?name=Spaghetti
    &description=Pairs nice with some mushrooms
    &category=Base

> {%
    // make sure ingredient was created
    client.assert(response.status === 201, "ingredient was not created")
    // save spaghetti_ingredient_id for next request
    client.global.set('spaghetti_ingredient_id', response.body.id);
%}

### @test post an onion with an image
POST /v1/ingredients
    ?name=Onion
    &category=Cat 2
accept: application/json
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="file"; filename="onion.jpg"
Content-Type: image/jpeg

< {{assetsDir}}/onion.jpg
--BOUNDARY--

> {%
    // make sure ingredient was created
    client.assert(response.status === 201, "ingredient was not created")
    // save onion_ingredient_id for next request
    client.global.set('onion_ingredient_id', response.body.id);
%}

### get the onion by the id
GET /v1/ingredients/{{onion_ingredient_id}}

### get the onion image
GET /v1/ingredients/{{onion_ingredient_id}}/image

### gets all ingredient object data from the filestore
GET /v1/ingredients/filestore-objects

### updates the onion data
PATCH /v1/ingredients/{{onion_ingredient_id}}
accept: application/json

{
    "category": "Cat 1"
}

### update the spaghetti image to be the same as the onion
PATCH /v1/ingredients/{{spaghetti_ingredient_id}}
accept: application/json

{
    "object_name": "onion.jpg"
}


### deletes the onion
DELETE /v1/ingredients/{{onion_ingredient_id}}

### check that the spaghetti object name was set to null
GET /v1/ingredients/{{spaghetti_ingredient_id}}

### gets all ingredient object data from the filestore
GET /v1/ingredients/filestore-objects
